config:
    delay-between-messages: 1000
debug:
    enabled: false
zones:
    chat:
        enabled: true
        excluded-filters:
    signs:
        enabled: true
        excluded-filters:
            - duplicate-messages
    anvil:
        enabled: false
        excluded-filters:
filters:
    duplicate-messages:
        default-level: 10
        priority: 5
    server-ip:
        default-level: 4
        priority: 1
    repeated-characters:
        default-level: 10
        priority: 2
        count: 5
    all-caps:
        default-level: 12
        priority: 3
    profanity:
        default-level: 10
        priority: 4
        expressions:
            "\\bf+uck+|f+uck+\\b": # "fuck"
                level: 30
            "\\bw+ank+|w+ank+\\b": # "wank"
                level: 15
            "\\bd+ick+|d+ick+\\b": # "dick"
                level: 20
            "\\bc+ock+|c+ock+\\b": # "cock"
                level: 22
            "\\bp+enis+|p+enis+\\b": # "penis"
                level: 20
            "\\bs+hit+|s+hit+\\b": # "shit"
                level: 10
            "\\bp+is+|p+is+\\b": # "piss"
                level: 7
            "\\bs+keet+|s+keet+\\b": # "skeet"
                level: 13
            "\\bb+itch+|b+itch+\\b": # "bitch"
                level: 15
            "\\bt+its+|t+its+\\b": # "tits"
                level: 12
            "\\bt+itties+|t+itties+\\b": # "titties"
                level: 12
            "\\bp+ussy+|p+ussy+\\b": # "pussy"
                level: 20
            "\\bc+unt+|c+unt+\\b": # "cunt"
                level: 25
            "\\bt+wat+|t+wat+\\b": # "twat"
                level: 12
            "\\bc+lit+|c+lit+\\b": # "clit"
                level: 15
            "\\ba+ss+|a+ss+\\b": # "ass"
                level: 10
            "\\bc+um+|c+um+\\b": # "cum"
                level: 22
            "\\bn+igger+|n+igger+\\b": # "nigger"
                level: 30
            "\\bf+aggot+|f+aggot+\\b": # "faggot"
                level: 25
            "\\bq+ueer+|q+ueer+\\b": # "queer"
                level: 25
